repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: trailing-whitespace
        exclude: '^(board/inc)|[tests/misra/coverage_table]/'
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
        exclude: '^(tests/automated)/'
-   repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
    -   id: flake8
        exclude: '^(tests/automated)/'
        args:
        - --ignore=E111,E114,E121,E501,E302,E305,W504
        - --exclude=python/esptool.py,tests/gmbitbang/*
        - --statistics
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: '^(tests/automated)/'
        args:
        - --disable=C,R,W0613,W0511,W0212,W0201,W0311,W0106,W0603,W0621,W0703,E1136
        - --generated-members="usb1.*"
